### ISSUE TITLE
Add a pipeline for generating micromasters report joining micromasters and bigquery data

### ISSUE THREAD

**Issue by abeglova** [mitodl/ol-data-platform#144]
Add a pipeline for joining the micromasters and bigquery data in the Athena cluster to generate the report and save it as a table to Athena. This will involve the following steps:

A sensor that waits for the micromasters and bigquery data update jobs to finish to launch the report generating pipeline
A solid per page in the linked sample report that generates a file that is indexed by Athena. The Athena tables will be exposed to bi users.

There are some manual adjustments made to this data in the mm_autorep codebase - a small number of users should have certificates but do not have certificates according to the bigquery edx database. For now we can store the list as a constant in this codebase but if we add more automated reports to ol-data-pipelines we can consider adding a “report_adjustments” repo similar to https://github.com/mitodl/open-resource-blocklists to make it easier to keep track of and add special case report adjustments as necessary.

**Comment by blarghmatey** [comment]
@pdpinch @abeglova can we close this now?
