### ISSUE TITLE
Create an Athena data cluster  table with enrollment data

### ISSUE THREAD

**Issue by abeglova** [mitodl/ol-data-platform#17]
Normalize data from the  MITx, xPRO, MicroMasters and Bootcamps files on S3 to create an enrollment data table in an Athena cluster

**Comment by blarghmatey** [comment]
There are a few moving pieces in making this happen.

- [ ] Populate Glue metadata catalog with table information for enrollment data sources
  - [ ] Determine mechanism for populating Glue catalog: Configure the Glue crawler, or use the Glue catalog API to generate the table metadata
  - [ ] If using the API, update the table metadata with any schema evolutions coming from the source tables
- [ ] Use DBT to build a transformation pipeline to generate a combined enrollments table from source data sets
  - [ ] Initialize DBT project
  - [ ] Integrate https://github.com/Tomme/dbt-athena/ as database driver
  - [ ] Determine common schema elements and design combined table schema
  - [ ] Write DBT tasks to build and incrementally update combined enrollments table

**Comment by blarghmatey** [comment]
For the time being we have used the Glue crawler interface to populate table data, though we will be moving to use the Glue API to more easily register and update table schemas as part of the pipeline execution (https://github.com/mitodl/ol-data-pipelines/issues/26).
