### ISSUE TITLE
Create bulk update pipeline for updating open enrollment data

### ISSUE THREAD

**Issue by abeglova** [mitodl/ol-data-platform#18]
Create a table in open with course enrollments by user.
The update pipeline will reside in ol-data-pipelines. The update will consist of the following steps:

1) Query the open data users and courses tables for an updated list of users and open course ids and upload the data to Athena. There should be and option to only upload the users created since the last run 

2) Run a sql join on Athena to filter  enrollment data to only enrollments by open users and join to open course ids. 

3) Upload updated enrollment data into open.

**Comment by pdpinch** [comment]
What changes will be needed in Open to allow for this? Does ol-data-pipelines already have access to Open's postgres tables? Does Open need an API to allow ol-data-pipeline to upload the updated data? 

How will retired accounts be handled (either retired in Open or retired in MITx)?

**Comment by abeglova** [comment]
The only change that is needed in open is adding the new table for storing the data.

 ol-data-pipelines  does not have access to the open postgres tables already, so the pipeline will need to be configured with database credentials. The data will be uploaded straight to the database table, so there won't be an api

Right now I am not doing anything special for retired accounts. I can filter out open accounts that are no longer active when pulling the open user emails
