### ISSUE TITLE
Create an AWS Glue resource for registering tables in Athena/Trino

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-data-platform#26]
In order to simplify creation of new tables in Athena/Trino as we land data into S3 we need a way to create table definitions in AWS Glue. To support that we would like to have a Dagster resource definition that provides a simple interface for registering schemas and datasets as part of the pipeline execution.

https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-catalog.html

**Comment by shaidar** [comment]
Is this still relevant?
