### ISSUE TITLE
Redash: Don't show "remote login" if we can't support Touchstone

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-data-platform#289]
I was testing login on https://redash-production.odl.mit.edu/login and the "Remote Login" button doesn't seem to function. Can we remove it?

**Comment by blarghmatey** [comment]
We are adding back the Touchstone integration and will remove the user/pass login option so that the experience remains the same as the current implementation.

**Comment by dseaton** [comment]
@blarghmatey I think we can close this issue. Note, it would be nice if we could rename "Remote Login" to "Touchstone".
