### ISSUE TITLE
Synchronize edx.org course exports to S3

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-data-platform#329]
# User Story
As an engineer working on MIT Open I would like to be able to integrate course contents from edx.org along with our other Open edX installations.

# Description/Context
IRX is maintaining a Google Cloud Storage bucket with the `.tar.gz` course bundles for courses being hosted on edx.org. All of our other Open edX installations have pipelines configured to load course bundles into date-stamped paths in S3 on a nightly basis. In order to reduce the level of development effort we would like to replicate that interface by synchronizing the GCS course exports to S3 using the same path formats. The pipeline code that manages that export is located at https://github.com/mitodl/ol-data-platform/blob/main/src/ol_orchestrate/ops/open_edx.py#L482-L576

The bucket in GCS that has the course bundles is `[simeon-mitx-course-tarballs](gs://simeon-mitx-course-tarballs)`

# Acceptance Criteria
- [x] There is a pipeline that replicates the course exports from edx.org from GCS to S3
- [x] The pipeline is triggered by a sensor that monitors for changes/new contents in the source GCS bucket

**Comment by shaidar** [comment]
The pipeline code that manages the export is located here - https://github.com/mitodl/ol-data-platform/blob/main/src/ol_orchestrate/ops/open_edx.py#L630-L704

**Comment by shaidar** [comment]
Looked into using our existing `bigquery` resource and mainly just changing the last line in yielding a storage client, however it appears that we have to create a separate resource (which was mainly copy/paste). Ran into a permissions issues using the existing creds to read from GCS and am working with Jon to see what permissions need to be tweaked on their end to resolve it.

**Comment by shaidar** [comment]
Chatted with Jon and it seems like this is not something he can do himself and is contacting IST to create a custom role for this to work.

**Comment by shaidar** [comment]
Checked in with Jon on Monday and he still hadn't heard anything. Will ping him again today to see if there are any updates.

**Comment by shaidar** [comment]
We now have access to the GCS bucket.

**Comment by shaidar** [comment]
Have most of the pipeline code written except for connecting the output from one op (downloading the files from GCS) to the input into the other op (uploading the assets to S3) which I will be working on today and then testing out on QA.

**Comment by shaidar** [comment]
Ran into some issues with the dagster container builds after adding the gcs pipeline. Tobias ended up making some changes to how we're building containers for pipeline use in dagster which ended up being a blocker, and now we're back to testing the pipeline on QA.

**Comment by shaidar** [comment]
Resolved some bugs in the pipeline code the last being a subfolder needed to be created before downloading the GCS bucket files. After resolving that, trying now to determine what S3 bucket to upload the data to. Appears that we have a bunch of [different buckets specified](https://github.com/mitodl/ol-infrastructure/blob/main/src/ol_infrastructure/applications/dagster/Pulumi.applications.dagster.QA.yaml#L10-L22), however not all of them actually have been created. Trying to determine why those buckets haven't been created and whether we want to stick to that way of doing things or whether we want to upload those files to an existing bucket within a subfolder.

**Comment by shaidar** [comment]
Sync on QA went through and course tarballs have been uploaded to QA bucket. Working on the following things now:
- Verify that the sensor is working whereby the dagster pipeline is triggered whenever a file is added to the GCS bucket
- Check with Matt on what permissions the open app requires for that bucket and add those in pulumi

**Comment by shaidar** [comment]
Still struggling to verify whether the sensor is functional. It doesn't show up in dagster and running `dagit` throws an exception. The sensor is meant to make a call to a job however we have things setup a bit differently and aren't using the `job` decorator. Tried a few different ways using `to_job` based on Dagster docs to resolve the issue, however haven't had much luck so far. Continuing to look through the docs and try a few different things to get the sensor working.

**Comment by shaidar** [comment]
Chatted with Tobias about it and he mentioned the newly introduced dagster [definitions](https://github.com/dagster-io/dagster/discussions/11167) feature that helped resolve the issue. [Change](https://github.com/mitodl/ol-data-platform/commit/4b335a1914f9d79743d8b910bc165f3c5e1e729f) was merged and will be verified on QA before deploying it to production on Monday.
