### ISSUE TITLE
Stage mitxonline users_user_groups

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-data-platform#335]
- [ ] what are the raw fields
- [ ] write up a plan for each field, including modifications to the field name, data types, data to omit, etc. 
- [ ] open a PR the implements the plan for `users_user_groups`

**Comment by abeglova** [comment]
The columns for this table are
id
user_id
group_id

group_id refers to the `auth_group` table and can be "Editor" or "Moderator". This is probably wagtail permissions. If we're not importing `is_staff` and `is_superuser` I think we can skip importing this for the time being.

**Comment by abeglova** [comment]
So no pr will be needed for this table

**Comment by rhysyngsun** [comment]
Agree on skipping.
