### ISSUE TITLE
Stage mitxonline users_legaladdress

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-data-platform#336]
- [x] what are the raw fields
- [x] write up a plan for each field, including modifications to the field name, data types, data to omit, etc. 
- [x] open a PR the implements the plan for `users_legaladdress`

**Comment by abeglova** [comment]
The users_legaladdress has the following columns 
    columns:
    - name: id
      description: int, primary key for table

keeping for now, dropping in the intermediate layer

    - name: country
      description: string, user country code

keeping as is

    - name: user_id
      description: int, foreign key to users_user

keeping as is

    - name: last_name
      description: string, user last name

keeping as is

    - name: created_on
      description: timestamp, when the record was created

Omitting - this is postgres internals and not really useful data 

    - name: first_name
      description: string, user first name

Keeping

    - name: updated_on
      description: timestamp, when the record was updated

Omitting - this is postgres internals and not really useful data
