### ISSUE TITLE
Stage mitxonline users_user_permissions

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-data-platform#337]
- [ ] what are the raw fields
- [ ] write up a plan for each field, including modifications to the field name, data types, data to omit, etc. 
- [ ] open a PR the implements the plan for `users_user_permissions`

**Comment by abeglova** [comment]
This table was either copied over from somewhere or generated with django boilerplate. I has no rows on production.

The columns are id, user_id and permission_id 

We can ignore it

**Comment by rhysyngsun** [comment]
Agree on ignoring it, we don't really use it in most of our other products since everyone is either a learner or they are staff/superuser. FWIW, this is a table that django implicitly generates for whatever the `AUTH_USER` model is so that's why it ends up namespaced under `user_*`.
