### ISSUE TITLE
Stage mitxonline users_blocklist

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-data-platform#338]
- [ ] what are the raw fields
- [ ] write up a plan for each field, including modifications to the field name, data types, data to omit, etc. 
- [ ] open a PR the implements the plan for `users_blocklist`

**Comment by Ferdi** [comment]
Don't we want to know if user is blocked.  Table can be empty now but it could have data in the future

**Comment by abeglova** [comment]
If a user is blocked is_active will be set to false on the the user. This table does have users, just hashed emails

**Comment by abeglova** [comment]
Theoretically we can use the same hash to join from users to this table using the emails to figure out if a user was blocked or was deactivated for some other reason but i think if we actually want that information we should just do a code change to add a column

**Comment by Ferdi** [comment]
Is it true that the existence of the user in this table is the equivalent of  `is_active = false` ?

**Comment by abeglova** [comment]
No. The function of this table is to keep a list of emails that users can't create new accounts with. That's different from deleting a user record. These emails are also hashed so they are hard to query/join to
