### ISSUE TITLE
Schemas not displaying for the QA Data Lake connection in Redash

### ISSUE THREAD

**Issue by dseaton** [mitodl/ol-data-platform#350]
Schemas are not loading for the QA Data Lake connection in Redash.

![Image](https://user-images.githubusercontent.com/1703442/192843770-e34220a8-33bd-4c38-b637-516a0bdc30a1.png)

**Comment by shaidar** [comment]
This is being discussed [here](https://github.com/mitodl/ol-infrastructure/issues/1149)

**Comment by dseaton** [comment]
Closing, as the work is being discussed/tracked here:https://github.com/mitodl/ol-infrastructure/issues/1149
