### ISSUE TITLE
course settings: url data path

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-data-platform#372]
### Steps to Reproduce

1. Look up a URL path in the [BI report ](https://bi.odl.mit.edu/queries/1194) such as `/home-page/courses/microeconomics/`

### Expected Behavior

- I'm not sure what to expect from the field name. 
- I think a link to the about page would be useful, but those URLs are constructed differently

### Actual Behavior

- I think the path is based on the page location and the page slug, neither of which is used in about page URLs.

**Comment by pdpinch** [comment]
Honestly, I think it would be fine just to remove this column. 

A knowledgeable user will know how to create about page URLs, using the contents of `courseware_id_readable` 

A link to the CMS page for editing might be useful, but I'm not sure how to calculate that.

**Comment by dseaton** [comment]
Closing this. If it is still a priority, let me know.
