### ISSUE TITLE
Stage mitxonline `courses_courserun`

### ISSUE THREAD

**Issue by rachellougee** [mitodl/ol-data-platform#382]
Stage mitxonline courses_courserun

- [ ]  list the fields for courses_courserun
- [ ]  plan for each field, including modifications to the field name, data types, data to omit, etc.
- [ ]  open a PR that implements it

**Comment by rachellougee** [comment]
A list of all the fields in courses_courserun

- **id**
  - integer field, the primary key to the table
  - Keep it, rename it to `course_run_id`
- **title**
  - varchar field, the title of the course run.
  - keep it, rename it to `course_run_title`
- **live**
  - boolean field
  - keep it, rename it to `is_course_run_live`
- **courseware_id**
  - varchar field
  - keep it
- **courseware_url_path**
   - varchar field
   - keep it
- **run_tag**
  - varchar field
  - A string that identifies the set of runs that this run belongs to. E.g. 1T2022
  - keep it? but this string is part of courseware_id
- **start_date** 
  - timestamp field
  - The day the course begins
  - keep it
- **end_date** 
   - timestamp field
   - The last day the course is active. 
   - keep it
- enrollment_start
   - timestamp field
   - The first day students can enroll 
   - drop it ? as this field is related to enrollment.
- enrollment_end
   - timestamp field
   - The last day students can enroll
   - drop it ? as this field is related to enrollment.
- expiration_date
   - timestamp field
   - The date beyond which the learner should not see the link to this course run on their dashboard.
   - drop it? as this is related to enrollment and it is not always populated
- upgrade_deadline
  - timestamp field
  - The date beyond which the learner can not enroll in paid course mode.
  -  drop it ? as this is related to enrollment and it is not always populated
- is_self_paced
  - boolean field,
  - this was added as part of the course certificate. It means a user can earn a certificate at any time and doesn't need to wait for the end date
  - drop it?
- **course_id**
  - integer field, the foreign key to `courses_course`
  - Keep it
- **created_on**
  - timestamp field
  - convert to ISO8601, rename it to `course_run_created_on`
- **updated_on**
   - timestamp field
   - convert to ISO8601, rename it to `course_run_updated_on`

We already staged this table, but I can make changes based on the new standard. @dseaton Does my plan make sense to you ? or any of these fields you think we should stage?
```
    select
        id
        , live
        , title
        , end_date
        , start_date
        , course_id
        , courseware_id
        , courseware_url_path
        , created_on
        , updated_on
    from source
```

**Comment by dseaton** [comment]
expiration_date, upgrade_deadline, and is_self_paced have all been used in recent reporting, so I would keep them. Also, I believe courseware_id is the same as the "courseware readable" field found in other tables. You might confirm and then match the name accordingly. 

Last, I am currently using enrollment_start and enrollment_end in a report (https://bi.odl.mit.edu/queries/1194/source). I would include them, even though it may seem redundant. We plan to provide dashboards about course settings and there can be useful distinctions.

**Comment by Ferdi** [comment]
I the staging layer we should be conservative about dropping fields.   No need to make assumption whether a particular field is needed or not.  Our data warehouse (intermediate layer) will be the single source of truth for all our data sources.
