### ISSUE TITLE
Stage mitxonline `courses_coursetopic`

### ISSUE THREAD

**Issue by rachellougee** [mitodl/ol-data-platform#383]
Stage mitxonline courses_coursetopic

 list the fields for courses_ccoursetopic
 plan for each field, including modifications to the field name, data types, data to omit, etc.
 open a PR that implements it

**Comment by rachellougee** [comment]
@dseaton @Ferdi Do you think we should bring in this table or wait? courses_coursetopic is blank on MITxOnline production, but @pdpinch said we might use it later, it's currently used in mitxpro

**Comment by dseaton** [comment]
I would not bring it in, as it would only cause confusion for analysts. There might also be a "feature" argument. I remember talking with Ferdi about a recent report for business ops. They wanted us to put placeholder fields in the report for future features (e.g., programs), but that made the SQL messy and led to misunderstandings about why the cells were empty.

**Comment by rachellougee** [comment]
For `courses_coursetopic`, It's straightforward as there are 4 fields
id
name
created_on
updated_on
