### ISSUE TITLE
Stage mitxonline `courses_course_topics`

### ISSUE THREAD

**Issue by rachellougee** [mitodl/ol-data-platform#384]
Stage mitxonline `courses_course_topics`

 list the fields for courses_course_topics
 plan for each field, including modifications to the field name, data types, data to omit, etc.
 open a PR that implements it

**Comment by rachellougee** [comment]
This table `courses_course_topics` has the following columns:

- id
- course_id
- coursetopic_id  (this is a foreign key reference to '[courses_coursetopic](https://github.com/mitodl/ol-data-platform/issues/383)`

Not sure if it makes sense to combine this table `courses_course_topics` with `courses_coursetopic` as these two tables can't be used without each other. I know our standard is to do the merge at the intermediate layer, but in this case, `courses_coursetopic` is just a lookup table with topic name and timestamp fields

If we combine the two tables together at the staging layer, we would lose the timestamp fields, that is when a topic is created

**Comment by abeglova** [comment]
I don't think the date when the topic was created is information we are going to use anywhere so I don't think that's a big deal but also it  makes sense to keep doing joins in the staging layer.

**Comment by Ferdi** [comment]
Can we look a bit closer at the code.  What do these 2 tables do and how are they suppose to work ? What part of our app is using them and how ? 
Why would we need 2 models to add tags to courses ?

**Comment by rachellougee** [comment]
@Ferdi These two tables are not used in MITxOnline at the moment. They are supposed to follow the mitxpro where it's used in the [course API](https://xpro.mit.edu/api/v1/courses/) consumed by open search.

```
    {
        "id": 29,
        "title": "Machine Learning, Modeling, and Simulation Principles",
        "description": "<p data-block-key=\"tkkr3\">Course 1 of 2 in the program <i>Machine Learning, Modeling, and Simulation: Engineering Problem-Solving in the Age of AI</i></p>",
        "thumbnail_url": "https://xpro-app-production.s3.amazonaws.com/original_images/ML-course-1-LOW_New.jpg",
        "readable_id": "course-v1:xPRO+MLx1",
        "courseruns": [],
        "next_run_id": null,
        "topics": [
            {
                "name": "Technology:AI/Machine Learning"
            }
        ]
    },
```
As for what these two tables do, `courses_coursetopic` is just a lookup table, `courses_course_topic` is used as a reference as to which topic_id is tagged in what course

courses_coursetopic
![image](https://user-images.githubusercontent.com/3138890/197575435-50f69fbb-c018-4d5d-a10d-df455156c51d.png)

courses_course_topic
![image](https://user-images.githubusercontent.com/3138890/197575602-531048af-94be-4d2b-bc0a-cdf03363abe9.png)

As for why we need 2 models to add tags, this is just to follow our standard if I remember correctly. We said to keep merging at the intermediate level. If it makes sense to combine two into one, we can do that

**Comment by Ferdi** [comment]
Thanks @rachellougee , that's helpful.

> As for why we need 2 models to add tags, this is just to follow our standard if I remember correctly. We said to keep 
> merging at the intermediate level. 

Yes, I agree.
