### ISSUE TITLE
Create Vault resource definition

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-data-platform#4]
In order to handle access to secrets and credentials we need to create a resource definition that interacts with Vault to retrieve data at runtime.

**Comment by shaidar** [comment]
Trying to determine whether it's best to fork [this](https://github.com/silentsokolov/dagster-hashicorp) and add support for AWS IAM auth or stick to what’s there and use token auth and add an env var to the dagster instance.

**Comment by blarghmatey** [comment]
Let's start with using it as-is, because I'm sure there are other modifications that we would like to add either in a fork, PR, or rebuild.

**Comment by shaidar** [comment]
Based on the readme, we basically just use it as a resource when we need it. So, what's the request here?
- Generate a token based on the dagster vault policy and set it up as a env var so that when we do use the vault resource, the env var is already defined and available?
- Something else?

**Comment by shaidar** [comment]
@blarghmatey The [dagster docs](https://docs.dagster.io/_apidocs/config#dagster.configured) mention that "Using configured may result in config values being displayed in Dagit, so it is not recommended to use this API with sensitive values, such as secrets."

**Comment by blarghmatey** [comment]
In that case, maybe we set the token as an env var to be consumed by the resource and then use it for fetching the paths that we need to access in the pipelines.

**Comment by shaidar** [comment]
When u talk about a resource, are u referring to a dagster resource similar to what u've done [here](https://github.com/mitodl/ol-data-platform/blob/main/src/ol_orchestrate/resources/healthchecks.py)? The way I read the doc on the `dagster-vault` is that it can be used just like we've done with `airbyte` for example. Just call it in the job that it's needed in.

**Comment by blarghmatey** [comment]
So, this plugin creates a resource, which is the same type of plugin as what I created with the Healthchecks resource that you linked to. The work to be done here is to weave the usage of that resource into the runtime (e.g. to populate the `DBT_TRINO` credentials). In order to avoid tight coupling with the Vault runtime for e.g. dev environments we might want to wrap it in a generalized `secret` interface.

I'm happy to help pair on this if it's useful to explore the problem space together.

**Comment by shaidar** [comment]
After some digging, think there’s a bug in dynaconf and vault. Based on [this] (https://github.com/dynaconf/dynaconf/blob/master/dynaconf/loaders/vault_loader.py#L90) if u have a blank value for that key, then dynaconf should just get the secrets from the path set in env file. But looking at the hvac code, it does a LIST on that path instead and since your keys are stored at the root of that path, it throws an InvalidPath error. https://github.com/hvac/hvac/blob/develop/hvac/api/secrets_engines/kv_v1.py#L36-L59

**Comment by blarghmatey** [comment]
With the use of [pydantic-vault](https://github.com/nymous/pydantic-vault) we are able to easily fetch secrets in pipeline definitions.
