### ISSUE TITLE
Intermediate `courses` models for MITxOnline

### ISSUE THREAD

**Issue by rachellougee** [mitodl/ol-data-platform#402]
# User Story
After courses-related tables are staged, we want to create intermediate `courses` related models for MITx Online

# Acceptance Criteria
- [ ] Plan for creating intermediate `courses_` tables
      - identify what fields need to be in Intermediate tables or bring in all the fields from staging?
      - and what tables should be combined to do the transformation 
      - ask for help if requirements are not clear
- [ ] Open PR to implement

**Comment by dseaton** [comment]
I have put together an initial list of fields based on the following resources:
- Discussion about "course products": https://github.com/mitodl/hq/discussions/236
- The course settings report used for MITx Online ecommerce launch: https://bi.odl.mit.edu/queries/1194/source
- Fields needed for business units, e.g., Customer Service: https://bi.odl.mit.edu/queries/1189/source

I am writing this under the assumption that we want to create an intermediate model for "course runs", as runs are what link other data (e.g., we join runs with orders, enrollments, etc).

### Minimal Fields
We have the following courserun fields in staging:
- courserun_title
- courserun_readable_id
- courserun_start_on
- courserun_end_on
- courserun_enrollment_start_on
- courserun_enrollment_end_on
- courserun_url
- courserun_is_self_paced
- courserun_upgrade_deadline
- courserun_blocked_country

### Potential Fields
Fields we should consider, but we either don't have them staged or they are related to ecommerce:
- "course modes", e.g., audit, verified, etc (not sure where we get this).
- `price`; we need significant `ecommerce` info before this will be available.
- "product is active"; a field that would let us know the product is available for purchase.
- "course description", this could be nice for end users, but would involve a lot of overhead related to cms/wagtail.

Others should feel free to continue adding here.

**Comment by rachellougee** [comment]
Thanks, @dseaton. Based on what we have staged for courses, here are my thoughts (combine with what Daniel suggested) on what fields and what tables go to the intermediate layer 

**Course Runs**
   (denormalize course data into courserun at this layer?)
- courserun_id
- courserun_title
- courserun_readable_id
- courserun_start_on
- courserun_end_on
- courserun_enrollment_start_on
- courserun_enrollment_end_on
- courserun_url
- courserun_is_self_paced
- courserun_upgrade_deadline
- **course_id**
- course_title
- course_readable_id
programs (TBD, This will be a 1:m relationship to the program that Nathan is working on)
   

**Course Blocked Country** 
- **course_id** 
- blockedcountry_code 

**Course Runs Topics** 
( Note that this table is empty on mitxonline, not sure if we should bring it to the intermediate layer yet)
 - **course_id** 
 - coursetopic_name

Course blocked country, and topic are 1:many relationship to Course, so it makes sense to be separate tables as the aggregation should probably happen in the mart depending on the use case (plus we don't know how data should be aggregated/piped at this layer yet)

@dseaton @Ferdi @pdpinch Not sure if this makes sense to you

**Comment by Ferdi** [comment]
How about : 


**Course**

course_id
course_title
course_readable_id
blockedcountries
topics

**Course run**

courserun_id
course_id
courserun_title
courserun_readable_id
courserun_start_on
courserun_end_on
courserun_enrollment_start_on
courserun_enrollment_end_on
courserun_url
courserun_is_self_paced
courserun_upgrade_deadline

**Comment by rachellougee** [comment]
@Ferdi I think that makes sense, the only issue is that I am not sure if we should aggregate blockedcountries and
topics at this layer, do we pipe them? If we pre-aggregate them, it would be hard to change the format at a later layer. Unless we come up with a format that the end user will accept?

**Comment by dseaton** [comment]
Are "blockedcountries" set for the run or the course?

**Comment by rachellougee** [comment]
> Are "blockedcountries" set for the run or the course?

Both blockcountries and topics are set for course, not run

**Comment by dseaton** [comment]
> > Are "blockedcountries" set for the run or the course?
> 
> Both blockcountries and topics are set for course, not run

Thanks!

**Comment by Ferdi** [comment]
@rachellougee  Good point.   Not sure why you are merging `courseruns` and `courses`  models into one.

**Comment by rachellougee** [comment]
@Ferdi I was debating whether to merge `courseruns` and `course` into one at the intermediate layer. The reason is that other data we are going to bring in like e-commerce products, enrollments, grades, and certificates are all tied into `courserun`, so we will likely use courserun more often than the course itself. But perhaps we can leave the merge at the mart layer?  If so, we can have the `course` and `courserun` as separate models in intermediate layer if it makes more sense
