### ISSUE TITLE
Create staging and intermediate models for MITxOnline CourseRun/ProgramRun Certificates + Grades

### ISSUE THREAD

**Issue by rachellougee** [mitodl/ol-data-platform#428]
# User Story
Create staging and intermediate models for user's CourseRun/ProgramRun certificates + grades from MITxOnline, so the data are available in a denormalized place

# Description/Context

- [ ] Identify tables needed to build staging and intermediate models for MITxOnline certificates and grades
- [ ] plan for each model, including modifications to the field name, data types, etc.
- [ ] open PR that implements the plan

**Comment by rachellougee** [comment]
- courses_courseruncertificate 
   - id
    - course_run_id
    - user_id
    - drop certificate_page_revision_id, uuid
- courses_programcertificate
  - id
  - program_id
  - user_id
  - drop certificate_page_revision_id, uuid
- courses_courserungrade
  - id
  - course_run_id
  - grade
  - user_id
  - passed

**Comment by Ferdi** [comment]
Not sure why you are dropping certificate_page_revision_id, uuid .

**Comment by rachellougee** [comment]
@Ferdi certificate_page_revision_id is the foreign key to wagtailcore_pagerevision, which is the table we mentioned in slack for the presentation. UUID is used to link the user's certificate https://rc.mitxonline.mit.edu/certificate/7d18e75a-dea8-432b-aab7-3c518f4668a8/. I thought we don't need it for now?

**Comment by rachellougee** [comment]
To be precise, both CourseRunCertificate and ProgramCertificate have a foreign key reference to `wagtailcore_pagerevision`, which is a table from CMS/Wagtail that doesn't exist in our staging model yet. That table is used here for tracking the content changes made to the specific course run certificates (e.g. add or remove signatories). I don't know the use case for that. Also if we need to bring certificate_page_revision_id to staging for some reason, then we would need to bring in wagtail data.
uuid is primarily used for linking a certificate (unique in URL), I can't think of a use case for that, but can keep it if necessary
