### ISSUE TITLE
Newly created model isn't available on OL data warehouse and redash

### ISSUE THREAD

**Issue by rachellougee** [mitodl/ol-data-platform#429]
### Steps to Reproduce
We recently added a new model ProgramCertificate to the MITxOnline app, it's available at https://mitxonline.mit.edu/admin/courses/programcertificate. 

But this model (called **courses_programcertificate**) isn't available on our data warehouse
![image](https://user-images.githubusercontent.com/3138890/199535207-34f05417-60ac-4bff-a71d-671625f22488.png)

or Redash

![image](https://user-images.githubusercontent.com/3138890/199535495-b40da45d-ae8f-42b0-9cb6-b05b1b2b5f13.png)

**Comment by rachellougee** [comment]
Just for reference, I am working on bringing over the program certificate as part of https://github.com/mitodl/ol-data-platform/issues/429, which needs this new table

**Comment by blarghmatey** [comment]
The replication of this database is failing in production due to the fact that it is syncing from a read replica that is seeing active updates. The updates from the primary cause active queries on the replica to be terminated (https://docs.airbyte.com/integrations/sources/postgres/#sync-data-from-postgres-hot-standby-server). I opened a PR to set the necessary parameter to allow for the replica queries to execute without interruption.

**Comment by rachellougee** [comment]
@blarghmatey Do we know when this will be resolved? No rush but if it's going to take a longer time, I can stage this new table at a later PR when it's ready

**Comment by blarghmatey** [comment]
Sorry. I was able to run the synchronization for MITx Online in production, and I implemented a code change in our infrastructure to resolve the underlying error. That will get released next week on Wednesday, but I will also make the update manually for now.

**Comment by blarghmatey** [comment]
The table is also showing now in BI

**Comment by rachellougee** [comment]
@blarghmatey Thanks. It looks like this model will be available ol_data_lake_production/qa next week
I am also a little confused about a field that seems to exist in ol_data_lake_production, but not ol_data_lake_qa. Could you take a look?

![image](https://user-images.githubusercontent.com/3138890/200043484-a97902ea-39cb-482c-8598-7ca364fbc741.png)

**Comment by blarghmatey** [comment]
Ok, this should be resolved in QA now. For future reference, the necessary change was to "Refresh Schema" in the Airbyte connection so that it would update the replication to include newly added tables and columns.
