### ISSUE TITLE
new source tables have duplicates in ol_data_lake_qa

### ISSUE THREAD

**Issue by rachellougee** [mitodl/ol-data-platform#465]
### Steps to Reproduce

There are two newly created tables from MITxOnline, that exist in our data lake in QA but have many duplicates (can tell by the primary key ID)
"ol_data_lake_qa"."ol_warehouse_qa_raw"."raw__mitxonline__app__postgres__courses_programrequirement"
"ol_data_lake_qa"."ol_warehouse_qa_raw"."raw__mitxonline__app__postgres__courses_programcertificate"

![image](https://user-images.githubusercontent.com/3138890/203395793-8e83f832-dce0-4915-aee4-70ce545b1601.png)

These newly created tables don't exist in our data lake on production for some reason.

The duplicate issues often get caught when running `dbt test` as we have certain tests to run against the generated staging and intermediate models. This is a known issue but is there a walkaround? If there is a way for acountadmin to delete, that's an option so that we don't get stuck with this issue in the QA environment

**Comment by dseaton** [comment]
Did this get resolved?

**Comment by rachellougee** [comment]
Looks like it's fixed now.
