### ISSUE TITLE
Staging and intermediate models for edx courses and enrollments

### ISSUE THREAD

**Issue by rachellougee** [mitodl/ol-data-platform#476]
# User Story
Look into edx courses and enrollments data and create corresponding staging and intermediate models, like what we have done for MITxonline, xPro and bootcamp

# Description/Context

## edx course metadata
Source table
 -  `raw__irx__edxorg__bigquery__mitx_course`
 -  https://github.com/MIT-IR/simeon/blob/main/simeon/upload/schemas/schema_mitx_course.json
    

## edx enrollments 
Source table
   - `raw__irx__edxorg__bigquery__mitx_person_course`
   -  https://github.com/MIT-IR/simeon/blob/main/simeon/upload/schemas/schema_person_course.json

**Comment by rachellougee** [comment]
A large number of enrollment data (874k as of today) in `person_courses` are missing user_id and most of the fields are blank, It looks like the same parsing issue is propagated into this table. That will need to be addressed from the source. We might need to filter these blanks until it's fixed
@dseaton FYI

**Comment by dseaton** [comment]
Thanks for letting me know. I'll reflect this in the doc.

**Comment by rachellougee** [comment]
@dseaton I mentioned to you some courses in person_courses that don't exist in mitx_courses. There are actually only 6 of them, not a lot.  Just FYI

MITx/CTL.CFx/1T18U5
MITx/CTL.CFx/1T18U8
MITx/Launch.x_3/1T2017
MITx/18.03Fx/2T2020
MITx/20.305x/1T2019
MITx/CTL.CFx/1T18U1

**Comment by dseaton** [comment]
Talked to Peter. The "*.CFx" courses are final exam courses, i.e., a course where a learner takes a final exam, but doesn't have other learner activity ([example](https://www.edx.org/course/supply-chain-comprehensive-exam)). We think this was an artifact before online proctoring. IMHO - I am ok that these courses aren't in mitx_courses. Whether we drop them or not from person course is something we should discuss.

I don't know why [18.03Fx](https://www.edx.org/xseries/mitx-18.03x-differential-equations) (part of an x-series) and [20.305x](https://learning.edx.org/course/course-v1:MITx+20.305x+1T2019/home) are not in "mitx_courses". We may need to ask.

[Launch.x_3](https://learning.edx.org/course/course-v1:MITx+Launch.x_3+1T2017/home) might be related to bootcamps in some way, but again, need to check why it isn't in the list.
