### ISSUE TITLE
Add "email_opt_in" table to data lake

### ISSUE THREAD

**Issue by dseaton** [mitodl/ol-data-platform#477]
# User Story
- As a user, I want to access a definitive list of user enrollments with appropriate unique identifiers, so I can more easily account for users in my analyses.

# Description/Context
IRx pointed out a table that can support our needs to identify unique users. This table is: 
- `email_opt_in`, which is in the `email_opt_in` dataset in BQ.

We would like to add the email_opt_in table to our data infrastructure so that we can stage the table.

# Acceptance Criteria
- [ ] `email_opt_in` data appears in the OL data lake.

**Comment by Ferdi** [comment]
I like how they name things

**Comment by dseaton** [comment]
I think this table is related to GDPR requests, but will be convenient for us in a different way.

**Comment by blarghmatey** [comment]
This has been set up in QA and is now running a sync. Once that has been completed and checked I will duplicate the setup in production.

**Comment by dseaton** [comment]
@rachellougee Can you check whether email_opt_in is still needed? And if not, close the issue?

**Comment by rachellougee** [comment]
In my opinion, email_opt_in is still needed. I found a small percentage of users' email and usernames are blank in person_course and user_info_combo, but they have email and usernames in this table. We could use this table to fill in these blanks.

**Comment by blarghmatey** [comment]
This is set up in QA and production.
