### ISSUE TITLE
Stage email_opt_in from BigQuery

### ISSUE THREAD

**Issue by rachellougee** [mitodl/ol-data-platform#487]
# User Story
Stage `email_opt_in` to our data platform when https://github.com/mitodl/ol-data-platform/issues/477 is done

# Description/Context
edx source https://edx.readthedocs.io/projects/devdata/en/stable/internal_data_formats/institution_data.html#email-opt-in-report
IR source https://github.com/MIT-IR/simeon/blob/main/simeon/upload/schemas/schema_email_opt_in.json
This table is useful to figure out the most recent email and username for MITx users on edx. If a user is enrolled in more than one of the courses, the user's email and username in this table should be the most recent ones

**Comment by rachellougee** [comment]
@dseaton I created this issue as you mentioned that this might be helpful to stage.  It's helpful to use it as a reference to figure out the user's most recent email, but this table is not one row per user, it's unique on user_id+course_id, which repeats the same user info for every course they enroll in, so we need to think about whether we need to stage this table as it is or aggregate it into one row per user.

**Comment by dseaton** [comment]
I would be ok with "staging" this model as is, then considering intermediate models that might make it easier to use (e.g., making a unique user model with only the latest info). Then we have the raw data staged and can create better tables in the next layers.

Note, please let me know if there are performance considerations. For example, if this just adds one more 12M row table that we have to parse/build every time we run dbt. Is that a concern?

**Comment by rachellougee** [comment]
Yes, there is a performance concern as this is a huge table, but it looks like it has a timestamp field which we might be able to use for incremental

**Comment by dseaton** [comment]
Got it.
