### ISSUE TITLE
MicroMasters program and program requirements

### ISSUE THREAD

**Issue by rachellougee** [mitodl/ol-data-platform#489]
# User Story
It would be useful to stage programs and program requirements from MicroMasters into our data infrastructure if we ever need to calculate program certificates

# Description/Context
We staged edx.org courses from IR BigQuery into our data platform, but there isn't normalized program information from edx, the only program-related field is "[micromasters_description](https://github.com/MIT-IR/simeon/blob/main/simeon/upload/schemas/schema_mitx_course.json#L150)", which has the following values:
- DEDP
- SDS
- POM
- Finance
- SCM

Since it is just a text field, we can't rely on this to figure out which edx course belongs to what program. These programs and requirements are in MicroMasters, especially the Non-DEDP ones. We've staged the DEDP program and program requirements from MITxOnline, but for the Non-DEDP programs, the source of truth would be MicroMasters

**Comment by rachellougee** [comment]
@Ferdi @pdpinch please let me know if you think it's worth staging.

**Comment by pdpinch** [comment]
Yes, I believe we will need this for #479
