### ISSUE TITLE
Add mitx_user_info_combo to OL data lake

### ISSUE THREAD

**Issue by rachellougee** [mitodl/ol-data-platform#502]
# User Story
Jon from IRx made an aggregated table - `mitx_user_info_combo` for us in BigQuery, which contains all the columns listed in https://github.com/MIT-IR/simeon/blob/main/simeon/upload/schemas/schema_user_info_combo.json , the existing one `user_info_combo` doesn't have all the columns, so we need `mitx_user_info_combo` instead.  please add this table to our data lake. thanks

# Acceptance Criteria
 `mitx_user_info_combo` appears in the OL data lake.

**Comment by shaidar** [comment]
Added table and running sync now. The last sync took close to 7 hours without that table.

**Comment by rachellougee** [comment]
@shaidar Thanks. mitx_user_info_combo is in the QA data lake, but it's not in production. It's not blocking me at the moment, just wanted to see if we are planing to add it on production as well

**Comment by shaidar** [comment]
The sync went through successfully and the table is in place now. Closing this issue

**Comment by shaidar** [comment]
That should be in production as well.
