### ISSUE TITLE
Stage Salesforce data 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-data-platform#529]
# User Story

Some example stories. This list shouldn't be considered complete. 

As a member of the xPRO team, I would like reports of revenue projections to include the actual revenue from B2B bulk enrollments, instead of an estimate. 

As a member of the Accounts Receivable team, I need to report on revenues per course for royalty purposes. For B2B bulk purchases, this requires a combination of enrollment data and actual per-seat revenue. 

# Description/Context

Peter has an account with access to read the salesforce data. 

# Acceptance Criteria
- [ ] Set up an airbyte connector to collect data from salesforce
- [ ] Review the available tables on salesforce data
- [ ] stage the relevant tables

**Comment by rachellougee** [comment]
To start, the relevant tables we need to stage to link b2b orders to Salesforce opportunity are:

- `raw__thirdparty__salesforce__opportunity` 
(cut off the person and account information) 
![image](https://user-images.githubusercontent.com/3138890/224426971-b77cfe2c-06d9-4b44-b3d2-bc70a5f95f47.png)


- `raw__thirdparty__salesforce__opportunitylineitem`

![image](https://user-images.githubusercontent.com/3138890/224426252-8d84bef4-93e9-4380-8212-d4c1196a90d8.png)

**Comment by pdpinch** [comment]
@blarghmatey airbyte fix was merged in https://github.com/airbytehq/airbyte/pull/24675

**Comment by blarghmatey** [comment]
This is set up in QA and production data lakes and the dbt models are deployed to production.
