### ISSUE TITLE
Sync Salesforce data using Airbyte

### ISSUE THREAD

**Issue by shaidar** [mitodl/ol-data-platform#535]
# User Story

Setup Salesforce as a data source and the data lake as its destination in Airbyte.
# Description/Context

- [ ] Account with admin privileges in Salesforce to setup a `[connected app]`(https://medium.com/@bpmmendis94/obtain-access-refresh-tokens-from-salesforce-rest-api-a324fe4ccd9b)
- [ ] Configure the source in Airbyte using the credentials from the `connected app`
  - [ ] QA
  - [ ] Production
- [ ] Test sync and verify that data is coming through 
# Acceptance Criteria
- [ ] 
Salesforce data is in the data lake.

**Comment by shaidar** [comment]
Ran into a blocker when trying to set this up whereby the Salesforce account provided to us didn't have the required permissions to create a `connected app`.

**Comment by pdpinch** [comment]
@blarghmatey what did you do on this to make it work? Can this be closed?

**Comment by blarghmatey** [comment]
The `Describe` table seems to have been the one that caused the failure that we were experiencing. I disabled that in the sync and it was able to complete, so we can close this issue now.
