### ISSUE TITLE
Create user course activities intermediate model 

### ISSUE THREAD

**Issue by rachellougee** [mitodl/ol-data-platform#548]
# User Story
Create an intermediate model for user course activities from edx.org dataset

# Description/Context

[person_course](https://github.com/MIT-IR/simeon/blob/main/simeon/upload/schemas/schema_person_course.json) contains some columns for user course activities, which is useful to add to our intermediate layer 

# Acceptance Criteria
- [ ] Identify user activities columns from person_course
- [ ] Create an intermediate model

**Comment by Ferdi** [comment]
Should we create a new models called  user_course_activity ? 

What would be some of the fields ?

- user_id
- course_id
- explored
- ... ?

**Comment by rachellougee** [comment]
Yes. It should be called something like user_course_activities (dbt recommends plural)
I am thinking about the following columns
- user_id
- course_id
- viewed
- explored
- first_event
- last_event
- ndays_act
- nplay_video
- nchapters
- nforum_* ?
- nprogcheck
- nproblem_check
- nvideo
- nvideos_unique_viewed
- nvideos_total_watched

should we add all these user activities columns there?

**Comment by rachellougee** [comment]
Looked into a bit where these columns come from

Aggregated from tracking logs for daily learner activities ([schema](https://github.com/MIT-IR/simeon/blob/main/simeon/upload/schemas/schema_person_course_day.json), [sql](https://github.com/MIT-IR/simeon/blob/main/simeon/report/queries/person_course_day.sql), [aggregated sql](https://github.com/MIT-IR/simeon/blob/main/simeon/report/queries/pc_day_totals.sql) )

- first_event
- last_event
- nevents
- ndays_act
- nplay_video
- nprogcheck
- nproblem_check
- ntranscript
- nshow_answer
- nvideo
- nseq_goto
- nseek_video
- npause_video
- avg_dt
- sdv_dt
- max_dt
- n_dt
- sum_dt

Users all forum activities that generated from mongo DB, not specifically for that course ([schema](https://github.com/MIT-IR/simeon/blob/main/simeon/upload/schemas/schema_pc_forum.json), [sql](https://github.com/MIT-IR/simeon/blob/main/simeon/report/queries/pc_forum.sql))
- nforum_*

@Ferdi I think we can add these learner's activities fields to the user_course_activities model, not certain about forum activities as these are not specific to the course, do we need these?

**Comment by Ferdi** [comment]
can we come up with more readable names for the fields ?

**Comment by rachellougee** [comment]
> can we come up with more readable names for the fields?

Yes, I will rename these fields to be more readable

**Comment by pdpinch** [comment]
Is this limited to edx.org courses, or do we get it from mitxonline, xPRO, and Residential MITx?

**Comment by rachellougee** [comment]
Forgot to leave a note for Peter's question. Currently, this is limited to edx.org courses.
