### ISSUE TITLE
Create intermediate model for MITx users

### ISSUE THREAD

**Issue by rachellougee** [mitodl/ol-data-platform#558]
# User Story
Create an intermediate model for MITx Users, where users are from edx and MITx Online
- edx users are mostly from BigQuery table `mitx_user_info_combo`, but it also includes users from `MITProfessionalX` and `MITxPRO` which should probably be excluded
- MITx Online users should be directly from our mitxonline app, but there is no profile data on mitxonline database. For these users who also have accounts in MicroMasters, we could get their profile data from MicroMasters if their account is linked to MITxOnline 

# Description/Context

# Acceptance Criteria
- [ ] MITx Users intermediate model is created in OL data lake

**Comment by rachellougee** [comment]
https://github.com/mitodl/ol-data-platform/issues/568 should be addressed before we work on this

**Comment by rachellougee** [comment]
As for my understanding, MITx user's data come from:

- MITx users on edx.org - this is in the BigQuery table `mitx_user_info_combo` we get from IRx
- MITx Online user's data from our application 

But the BigQuery table `mitx_user_info_combo` also includes users from
- `MITProfessionalX` e.g. MITProfessionalX/IOTx/2017_T2
-  MITxPRO courses. e.g. MITxPRO/SysEngxB2/1T2019
-  Our open edx users - we can exclude them because we can get these directly from our app

Do we exclude these users from `MITProfessionalX` and old MITxPRO courses listed at https://bi.odl.mit.edu/queries/1233/source?
@Ferdi @pdpinch 
Let me know if there is something else I am missing

**Comment by pdpinch** [comment]
MITProfessionalX and MITxPRO learners are not MITx learners. They should not be included in the MITx user data.
