### ISSUE TITLE
MITx report for active courses and instructors

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-data-platform#561]
# User Story
As a residential MITx educational technologist I would like to be able to get a list of instructors and courses that are active on the platform.

# Description/Context
At the start of each semester the educational technologists will archive old courses, so they need to know which instructors have active courses so they can be contacted. To get this list we need to run a query against the MySQL data from the Open edX platform.

# Acceptance Criteria
- [ ] There is an easily accessible and up to date report for the educational technologists that has the list of courses and instructors.

# Notes
The SQL that I have been executing manually to get this list is as follows:
```
SELECT
    u.username
    ,u.first_name
    ,u.last_name
    ,u.email
    ,sc.course_id
    ,sc.role
FROM
    "ol_warehouse_production_raw"."raw__mitx__openedx__mysql__auth_user" u
JOIN
    "ol_warehouse_production_raw"."raw__mitx__openedx__mysql__student_courseaccessrole" sc on u.id = sc.user_id
WHERE
    sc.role = 'instructor'
AND
    sc.course_id LIKE '%2022%' OR sc.course_id LIKE '%2023%';
```

**Comment by blarghmatey** [comment]
FYI @pdpinch

**Comment by rachellougee** [comment]
@blarghmatey @pdpinch Do we expect to generate this report based on the tables we get from IRx BigQuery? If so the residential source data isn't available yet.
If we want to generate this report directly from our open edx tables, these two are blank on the production data lake.

**Comment by pdpinch** [comment]
@blarghmatey @rachellougee checking in on this again. Do we have the necessary Residential MITx data available to create this report?

**Comment by rachellougee** [comment]
> Do we have the necessary Residential MITx data available to create this report?

I just checked that the two Residential MITx tables mentioned are in our staging models and there are data available.

**Comment by rachellougee** [comment]
@pdpinch @blarghmatey We should be able to report this using `int__combined__user_course_roles`. Here is an example 
https://bi.odl.mit.edu/queries/1347

**Comment by pdpinch** [comment]
Looks good to me. Now we just need to remember this report exists when Kaleb ask next, probably in June.
