### ISSUE TITLE
Add Bootcamp application related tables to staging and intermediate

### ISSUE THREAD

**Issue by rachellougee** [mitodl/ol-data-platform#578]
# Description/Context

In order to reproduce this report using tables in data lake https://bi.odl.mit.edu/queries/969/source, we need to add the following tables to staging 

- applications_bootcampapplication
- applications_applicationstep
- applications_bootcamprunapplicationstep
- applications_applicationstepsubmission
- klasses_installment

# Acceptance Criteria
- [ ] Stage the above tables

**Comment by rachellougee** [comment]
Related issue https://github.com/mitodl/hq/issues/847

**Comment by pdpinch** [comment]
Can this be closed?

**Comment by rachellougee** [comment]
> Can this be closed?

These tables are not staged in our data platform. I think we still need these tables to replace report like https://bi.odl.mit.edu/queries/969/source unless you disagree?

**Comment by rachellougee** [comment]
@KatelynGit FYI, `int__bootcamps__applications` in https://github.com/mitodl/ol-data-platform/pull/1018 should have all the non user profile related fields for replacing report https://bi.odl.mit.edu/queries/969/source. There are a lot of user profile fields in that report but you can pull from int__bootcamps__users
