### ISSUE TITLE
Stage Residential MITx open edX data

### ISSUE THREAD

**Issue by rachellougee** [mitodl/ol-data-platform#595]
# Description/Context

After the residential MITx open edX tables are ingested into our data lake https://github.mit.edu/IR/simeon-internal/issues/28, we need to stage the data similarly to MITxOnline and xPro open edx

**Comment by rachellougee** [comment]
There isn't a course table for MITx Residential in BigQuery. I am not sure where we can get a list of courses metadata listed https://lms.mitx.mit.edu/courses and also enrollment data 

The only table from BigQuery we can stage is `mitx_person_course`, which contains user activities fields

@blarghmatey @pdpinch

**Comment by rachellougee** [comment]
The list of tables we should stage are:

-  `raw__mitx__openedx__mysql__auth_user` for users
-  `raw__mitx__openedx__mysql__auth_userprofile` possibly but most of the fields are not collected
- `raw__mitx__openedx__mysql__course_overviews_courseoverview` for course data
-  `raw__mitx__openedx__mysql__student_courseenrollment` for enrollment
- `person_course` from BigQuery for user activities

@pdpinch @Ferdi let me know if that's what we need for the moment

**Comment by pdpinch** [comment]
How does this differ from the tables we collect for other open edX instances?

**Comment by rachellougee** [comment]
For MITxOnline and xPro, we collect users, courses, and enrollments from our Django app instead of from the open edx MySQL database. Since residential is different, these are only available from the open edx database unless I am missing something.

**Comment by rachellougee** [comment]
Residential open edx sync is blocked by https://github.com/mitodl/ol-data-platform/issues/609.

**Comment by rachellougee** [comment]
The following source tables are staged to our data lake. I will work on Residential BigQuery tables as part of https://github.com/mitodl/ol-data-platform/issues/626 once it's unblocked
raw__mitx__openedx__mysql__auth_user
raw__mitx__openedx__mysql__student_courseaccessrole
raw__mitx__openedx__mysql__course_overviews_courseoverview
raw__mitx__openedx__mysql__student_courseenrollment
raw__mitx__openedx__mysql__grades_persistentcoursegrade
