### ISSUE TITLE
Update Dagster code to use Pythonic Config

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-data-platform#654]
# User Story
- As a data engineer I want to stay up to date with Dagster's API design

# Description/Context
Dagster recently updated their APIs to support Pydantic-based config models and are promoting them in place of the previous dictionary objects passed into decorators. This is a more robust and easy to use/understand interface that we would like to adopt. They have created a migration guide [here](https://docs.dagster.io/guides/dagster/migrating-to-pythonic-resources-and-config)

# Acceptance Criteria
- [ ] All Dagster code uses the new Pythonic config interface

**Comment by quazi-h** [comment]
Updated all ops and jobs, working on updating resources.

**Comment by pdpinch** [comment]
Are there PRs that we can link in here?
