### ISSUE TITLE
MicroMasters alumni report since 2/15/2023

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-data-platform#700]
# User Story

As an admin in MIT Alumni Association, I need periodic updates of learners who have completed MicroMasters programs so I can invite them to join the MITAA.

As part of the work on #563, we delivered an update through 2/15/2023. It's time now to deliver an update through 5/31/2023, including recent additions from SDS, SCM and DEDP.  

# Acceptance Criteria

Our practice has been to drop an Excel file on [dropbox](https://www.dropbox.com/sh/uk9op9acclrahf5/AAAKxhBotwaTzzKHSmlZfr2Pa?dl=0) with the list of updated credential holders and their profile data. If there is a more convenient and self-service way to do this, please propose something here. 

# Related Issue
The SDS team has requested a similar report with just their users: https://github.com/mitodl/hq/issues/1471

**Comment by rachellougee** [comment]
@pdpinch Since you were asking for "an update through 5/31/2023", should we wait until the end of the month? I generated an updated list but it's from 02/15 to today. Is that ok?

**Comment by pdpinch** [comment]
We need to make sure it includes the DEDP course and program certificates that were generated on Monday. I had written down 5/31 because I wasn't sure how long it would take the team to finish grading, but they finished last week.

**Comment by rachellougee** [comment]
I've checked that 47 DEDP certificates that were generated on 05/22 are included in the file. I've dropped it in https://www.dropbox.com/home/micromasters%20test%20data%20for%20alumni @pdpinch FYI

**Comment by rachellougee** [comment]
This is done
