### ISSUE TITLE
Translate all tracking logs to consistent format

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-data-platform#737]
# Description/Context
Our historical tracking logs are an inconsistent mess of different structures and data types across the contained fields. In particular, the `event` field flip-flops between string and object in the data, old records that were shipped with FluentD have the `time` field as an integer timestamp, whereas newer logs shipped with Vector are rendered as strings. 

In order to be able to consume new logs going forward I added configuration to Vector to only parse JSON objects to the depth of the root node so that nested JSON will be serialized as an escaped string. For our historical data we need to transform it into a consistent structure with the more recent logs.

# Plan/Design
[DuckDB](https://duckdb.org/) has support for reading JSON files from S3 with the combination of the `httpfs` and `json` plugins. This lets us pull the tracking log data into a high-performance multi-core single-node SQL engine so that we can use SQL to transform the data and then write it back out to S3.

The flow would be to set up like so:
```sql
INSTALL httpfs ;
INSTALL json ;
LOAD httpfs;
SET s3_access_key_id="...";
SET s3_secret_access_key="...";
SET s3_region="us-east-1";
CREATE TABLE tracking_logs AS SELECT * FROM read_ndjson_auto("s3://mitxonline-qa-edxapp-tracking/logs/**", FILENAME=1);
```

We could probably get it to automatically handle the chunking of data and writing it back out to S3 in a single invocation if we need to.

**Comment by quazi-h** [comment]
Tested duckDB's capabilities to handle the tracking log data transformation. Was able to get new files with properly escaped nested objects. See https://gist.github.com/quazi-h/3ad0676549ebfe51b8e225acd17e39aa for the logic to read and transform log files using python and duckDB.

Had some open questions to go over with Tobias:
- input parameters to this script should be?
	s3 bucket?
- how to handle credentials for this script?
- need an IAM user with write privs to test writing of data back to S3
- how should we chunk up the work?
	- one download per thread?
	- process one table per file at a time vs one table per date?
	- there is a HIVE_PARTITIONING option that will produce an extra field with the partition name (is the source hive partitioned?)
- are we simply converting the nested objects into escaped strings in the output to replace the older files or are we utilizing duckdb to do what airbyte is doing?
- with duckdb it is possible to unpack the values in the nested objects using json_transform
- how to enforce datatype?
	- manually specify schema and datatypes gets final data to the escaped strings
		issues: if not specified, columns are dropped
	- load the table with auto-detect and convert context + event to strings?
		issues: nested double quotes in context are converted to single quotes. what if we encounter a new field that is an object?
	- load the table with auto-detect, query information schema for all fields that are not varchar, alter table to make them varchar
		issues: will be a little slower

**Comment by quazi-h** [comment]
The final changes have been applied to new pipeline to get it working and we have confirmed successful normalization when running locally. The PR above has been merged. The plan is to let the pipeline run on QA into the weekend and if successful, run against production. Once this is complete, we just need to kick off the Airbyte tracking log pipelines to get the log files ingested into the data lake, unblocking Rachel. Once this is done we can close this ticket.

**Comment by blarghmatey** [comment]
The pipeline logic has been deployed and the backfills have been run, but in the initial deployment there was a bug in the logic that caused invalid and non-normalized files to be uploaded. The source of the issue was that the DuckDB database file was hard-coded so that it got re-used across concurrent runs, meaning that there were race conditions as to which data was read in, in which order, and which tasks got around to writing the files out first. This also meant that sometimes non-transformed data was written out by a parallel process before the owning process got to the step of executing the transformations.

The source of the bug has been addressed, but there are an unknown number of days worth of data that are potentially invalid. To resolve the situation we are going to delete the transformed log files from S3 and re-run the backfills now that the fixed code is deployed.

**Comment by blarghmatey** [comment]
The data ranges that need to be deleted from S3 are:
- xPro QA - `2021-03-31` through `2023-06-27`
- xPro Production - `2019-08-28` through `2023-06-28`
- MITx QA - `2021-03-10` through `2023-06-27`
- MITx Production - `2017-06-13` through `2023-06-27`
- MITx Online QA - `2021-07-26` through `2023-06-23`
- MITx Online Production - `2021-08-18` through `2023-06-28`
