### ISSUE TITLE
Streamline deployment of dbt code changes to production

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-data-platform#767]
# User Story

- As a data analyst, I want to reduce friction in deploying dbt code, so I can maintain velocity with my work and know when my changes are live for consumers

# Description/Context

The current means of deploying new/udpated dbt models to the production environment does not fit with the workflow patterns of how the code is tested and validated. The desire is that as soon as new dbt code is merged to the `main` branch then it gets deployed straight to production.

## State of the world today
The current path to production for dbt code is rather convoluted.
1. dbt code gets merged to `main`
2. Concourse builds a new container in [this pipeline](https://cicd.odl.mit.edu/teams/main/pipelines/build-and-publish-dagster-containers). The Dockerfile concerned with dbt is [here](https://github.com/mitodl/ol-data-pipelines/blob/main/dockerfiles/orchestrate/Dockerfile.dbt_pipeline)
3. Once the container is built, a new Dagster AMI is built, including the docker-compose file found [here](https://github.com/mitodl/ol-infrastructure/blob/bump_pydantic_v2/src/bilder/images/dagster/templates/docker-compose.yaml.j2). The specific block for the dbt pipeline is [here](https://github.com/mitodl/ol-infrastructure/blob/bump_pydantic_v2/src/bilder/images/dagster/templates/docker-compose.yaml.j2#L34-L42). That is managed by the pipeline [here](https://cicd.odl.mit.edu/teams/infrastructure/pipelines/packer-pulumi-dagster)
4. After steps 1-3 complete, the code is in QA. Someone then needs to manually click the button to trigger a build for the Production stack of the Dagster Pulumi project in the [Dagster pipeline](https://cicd.odl.mit.edu/teams/infrastructure/pipelines/packer-pulumi-dagster)

# Acceptance Criteria

- [ ] When dbt code is merged to `main` it gets deployed to production automatically

# Plan/Design

**Comment by Ardiea** [comment]
"It might even be a case of splitting the runtime so that we pack the different containers onto different hosts/services since Dagster is already architected to allow for federating to different gRPC hosts that run the relevant code."
