### ISSUE TITLE
Permission issue running dbt code using production schema in QA cluster

### ISSUE THREAD

**Issue by rachellougee** [mitodl/ol-data-platform#793]
# Description/Context

As data analysts, we would like to run dbt code on the `dev_qa` target but use the production schema because QA data is often not useful

- database: ol_data_lake_qa
- schema: ol_warehouse_production_dev
- host: mitol-ol-data-lake-qa-0.trino.galaxy.starburst.io

This is the error I got when running dbt code against dev_qa
`
  TrinoExternalError(type=EXTERNAL, name=HIVE_METASTORE_ERROR, message="User: arn:aws:sts::610119931565:assumed-role/data-lake-query-engine-role-qa/trino-session is not authorized to perform: glue:CreateDatabase on resource: arn:aws:glue:us-east-1:610119931565:database/ol_warehouse_production_rlougee_staging because no identity-based policy allows the glue:CreateDatabase action (Service: AWSGlue; Status Code: 400; Error Code: AccessDeniedException; Request ID: ee46b622-8933-492b-b914-c0b358b6b3c8; Proxy: null)", query_id=20230809_185544_08799_3cv42)
`

## Expected Behavior

Run dbt code against `dev_qa` using schema `ol_warehouse_production_dev` successfully

**Comment by rachellougee** [comment]
@blarghmatey FYI, this is the issue we talked about.

**Comment by pdpinch** [comment]
@blarghmatey @rachellougee has this been fixed?

**Comment by rachellougee** [comment]
This can be closed. We can now use `dev_production` to create separate dev schema in production database as oppose to `dev_qa`
