### ISSUE TITLE
Replace the non-dedp  program certificate data with data from raw__edxorg__program_learner_report

### ISSUE THREAD

**Issue by abeglova** [mitodl/ol-data-platform#852]
Currently for non-dedp learners we generate data on program certificates earned from course certificates and program requirements.  The logic is in intermediate.micromaters.subqueries.__micromasters_program_certificates_non_dedp.

It would be nice if we could get this data directly from  edxorg. We recently staged "ol_data_lake_production"."ol_warehouse_production_raw"."raw__edxorg__program_learner_report" which should have this data.

First we need to determine if that table has all the relevant data.

**Comment by abeglova** [comment]
```SELECT count(distinct "user id") FROM "ol_data_lake_production"."ol_warehouse_production_raw"."raw__edxorg__program_learner_report"
```
Does returns Supply Chain Management and Finance but not Statistics and Data Science or Principles of manufacturing

**Comment by abeglova** [comment]
`SELECT count(distinct "user id") FROM "ol_data_lake_production"."ol_warehouse_production_raw"."raw__edxorg__program_learner_report"
where "program title" = 'Supply Chain Management'  and "date program certificate awarded" != 'null'`
Returns 3247 which is fewer than the 4500 program certificates we expect

**Comment by abeglova** [comment]
`SELECT count(*) FROM "ol_data_lake_production"."ol_warehouse_production_raw"."raw__edxorg__program_learner_report"
where "program type" = 'MicroMasters'` returns way more rows than expected - 30, 683,355 when our data says there should be 3,176,267 micromasters enrollments. Maybe there are duplicates?

**Comment by rachellougee** [comment]
```
SELECT distinct username
FROM "ol_data_lake_production"."ol_warehouse_production_raw"."raw__edxorg__program_learner_report" 
where "program title" = 'Supply Chain Management' and "completed program" ='True'
```
This returns 4521 learners from learners report

```
select distinct (user_edxorg_username) from "ol_data_lake_production"."ol_warehouse_production_mart"."marts__micromasters_program_certificates"
where program_title = 'Supply Chain Management'
```
Our mart says 4500. One learner didn't complete `CTL.CFx` but in learner's report, it's considered complete

**Comment by pdpinch** [comment]
@rachellougee can you link me to a report where I can review the discrepancies in the SCM credential holders? We may need to pass some details along to the SCM team to review.

**Comment by rachellougee** [comment]
`raw__edxorg__program_learner_report` isn't staged yet, so I can't link a query in BI, but it can be ran from https://mitol.galaxy.starburst.io/query-editor

```
with scm_in_learner_report as (
SELECT distinct username
FROM "ol_data_lake_production"."ol_warehouse_production_raw"."raw__edxorg__program_learner_report" 
where "program title" = 'Supply Chain Management' and "completed program" ='True'
),
 

 scm_in_mart as (
select distinct (user_edxorg_username) from "ol_data_lake_production"."ol_warehouse_production_mart"."marts__micromasters_program_certificates"
where program_title = 'Supply Chain Management'
 )

 select scm_in_learner_report.username
 from scm_in_learner_report
 left join scm_in_mart on scm_in_learner_report.username = scm_in_mart.user_edxorg_username
 where scm_in_mart.user_edxorg_username is null
```

I am using `completed program` in `raw__edxorg__program_learner_report`, but there is also a field called `date program certificate awarded`. If we use `date program certificate awarded` instead of `completed program`, then it's 3247. so there are learners who `completed program` but no `date program certificate awarded` ("completed program" ='True'  AND "date program certificate awarded" = 'null') in learner's report

**Comment by rachellougee** [comment]
We are missing "Statistics and Data Science", "Statistics and Data Science" and "Principles of Manufacturing" in `raw__edxorg__program_learner_report`.  Strange that `Principles of Manufacturing` exists in `raw__edxorg__program_cohort_report` but not `raw__edxorg__program_learner_report`.

**Comment by rachellougee** [comment]
Good new that "Finance" program seem to match between our mart and learner report
```
--158 in learner report
SELECT count(distinct username) 
FROM "ol_data_lake_production"."ol_warehouse_production_raw"."raw__edxorg__program_learner_report" 
where "program title" in ('Finance', 'MIT Finance') and "completed program" ='True'

---158 in our mart
select distinct (user_edxorg_username) from "ol_data_lake_production"."ol_warehouse_production_mart"."marts__micromasters_program_certificates"
where program_title = 'Finance'

**Comment by pdpinch** [comment]
Here are the first two rows of the "Statistics and Data Science" file learner_report__2023-10-02.csv

AUTHORING INSTITUTION | PROGRAM TITLE | PROGRAM UUID | PROGRAM TYPE | USER ID | NAME | USERNAME | USER KEY | COURSE TITLE | COURSE RUN KEY | COURSE RUN START DATE | EXTERNAL COURSE KEY | USER ROLES | TRACK | PURCHASED AS BUNDLE | GRADE | LETTER GRADE | DATE FIRST ENROLLED | DATE LAST UNENROLLED | CURRENTLY ENROLLED | DATE FIRST UPGRADED TO VERIFIED | COMPLETED PROGRAM | DATE PROGRAM CERTIFICATE AWARDED | COMPLETED | DATE COMPLETED | LAST ACTIVITY DATE
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
MITx | Statistics and Data Science | 71c95834f6df4f788cd7c6461dd9b1d4 | MicroMasters | 17491096 | Maria Tsyplukhina | mtsyplukhina | null | Introduction to Probability - The Science of Uncertainty | course-v1:MITx+6.041x_4+1T2017 | 2017-01-12 15:00:00 Z | null | null | audit | FALSE | 0 |   | 2018-01-11 00:00:00 Z | null | TRUE | null | FALSE | null | FALSE | null | 2023-01-01

I don't know, but I presume that "Authoring Institution" is equivalent to org.

**Comment by rachellougee** [comment]
I've looked over the data after Tobias did a re-sync from S3. Here are a summary:

- Finance and MIT Finance
   - **161** in `raw__edxorg__program_learner_report` ("completed program" ='True')
   - **158** in `marts__micromasters_program_certificates`
   - 3 learners who completed course-v1:MITx+15.455x+2T2023 and rewarded on 2023-10-23. This data has not reflected in BigQuery yet
   
- Supply Chain Management
   - **4521** in `raw__edxorg__program_learner_report` ("completed program" ='True')
   - **4500** in `marts__micromasters_program_certificates`
   -  I've looked one learner who didn't earn certificate for `course-v1:MITx+CTL.CFx+1T2023` per data from BigQuery. However, this learner has rewarded program certificate on 2023-06-08 in learner's report

- Principles of Manufacturing
    - **249** in `raw__edxorg__program_learner_report` ("completed program" ='True')
   - **249**  in `marts__micromasters_program_certificates`

We are still missing `Statistics and Data Science`. I've checked S3 bucket that @blarghmatey pointed out, I don't see this program under edxorg-program-credentials/reports_v2/MITx/. I am not sure why it is missing.

I think I can at least add `raw__edxorg__program_learner_report` to staging and intermediate, so it's available in BI until we are ok with swapping the MicroMasters program data and using from learner's report. @pdpinch Not sure if you prefer this way

**Comment by pdpinch** [comment]
> Finance and MIT Finance
> 3 learners who completed course-v1:MITx+15.455x+2T2023 and rewarded program certificate on 2023-10-23. This data has not reflected in BigQuery yet

2023-10-23 is 3 weeks in the future? 

> Supply Chain Management
I think I'll have to work with the MITx team to investigate these. Can you give me a csv or excel dump (or BI link) of the mismatched rows in raw__edxorg__program_learner_report

> Statistics and Data Science
I think @blarghmatey will have to follow up with 2U. If it helps, I can try to retrieve the relevant paths and filenames to pass along. 

@blarghmatey is it too hacky to try to inject the files that I have access to?

**Comment by rachellougee** [comment]
> Finance and MIT Finance
> 3 learners who completed course-v1:MITx+15.455x+2T2023 and rewarded program certificate on 2023-10-23. This data has not reflected in BigQuery yet

Yes, this 3 learners's `date program certificate awarded` for this program are all 2023-10-23 (3 weeks in the future)

>Supply Chain Management

@pdpinch I've added the mismatch in https://docs.google.com/spreadsheets/d/1ImlJijig8dj1ohE587oEyo4xmhzozDBCULhLcWiNjKY/edit#gid=0. It's MicroMasters folder in open learning engineering google drive.

**Comment by rachellougee** [comment]
* Statistics and Data Science
    * 1269 in marts__micromasters_program_certificates
    * 1273 in raw__edxorg__program_learner_report (`where  "completed program" ='True' and "program title" in ('Statistics and Data Science', 'Statistics and Data Science (General track)'`) 
   
It seems like these 4 learners don't have certificates for Capstone Exam `DS.CFx`, not sure if it exists back in 2018-1019 yet.

@pdpinch I added all the missing program certificates to https://docs.google.com/spreadsheets/d/1ImlJijig8dj1ohE587oEyo4xmhzozDBCULhLcWiNjKY/edit#gid=1277262405

**Comment by rachellougee** [comment]
Updated counts for MicroMasters programs on 11/03
- Finance and MIT Finance

167 in raw__edxorg__program_learner_report ("completed program" ='True')
167 in marts__micromasters_program_certificates

- Supply Chain Management

4521 in raw__edxorg__program_learner_report ("completed program" ='True')
4500 in marts__micromasters_program_certificates

- Principles of Manufacturing

257 in raw__edxorg__program_learner_report ("completed program" ='True')
251 in marts__micromasters_program_certificates

- Statistics and Data Science

1269 in marts__micromasters_program_certificates
1273 in raw__edxorg__program_learner_report ("completed program" ='True' and "program title" in ('Statistics and Data Science', 'Statistics and Data Science (General track)')

**Comment by pdpinch** [comment]
In all cases, there is more data in the`raw__edxorg__program_learner_report`  data set than in`marts__micromasters_program_certificates`, which seems appropriate since the latter depends on a slower pipelines of data from edX. 

I'm still interested in reviewing a list of the discrepancies, but I think the time has come to move ahead and update our mart so that the non-DEDP users are pulled from `raw__edxorg__program_learner_report`. We still need to supplement user profiles with any data we have available.

**Comment by rachellougee** [comment]
https://github.com/mitodl/ol-data-platform/pull/920 is to update our intermediate and mart for MicroMasters non DEDP certificates to pull from learners report. I've also kept one user in our [overwrite list ](https://github.com/mitodl/ol-data-platform/blob/main/src/ol_dbt/models/staging/micromasters/stg__micromasters__app__user_program_certificate_override_list.sql#L3) for SCM as the other 4 users are already in learners report.

As for a list of discrepancies, it's still the same list https://docs.google.com/spreadsheets/d/1ImlJijig8dj1ohE587oEyo4xmhzozDBCULhLcWiNjKY/edit#gid=1277262405 for SCM and SDS. Finance and Principles of Manufacturing are fine now and they don't have discrepancies. @pdpinch
